build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
            environment:
                mongodb:
                    version: '3.2'
                php:
                    version: '7.1.12'
        tests: true
filter:
    paths:
        - 'src/DependencyInjection/*'
        - 'src/Profiler/*'
        - 'src/Tests/*'
        - 'src/SitetheoryProfilerStorageBundle.php'
checks:
    php:
        code_rating: true
        duplication: true
build_failure_conditions:
    - 'elements.rating(<= C).new.exists'                        # No new classes/methods with a rating of C or worse allowed
    - 'issues.severity(>= MAJOR).new.exists'                    # New issues of major or higher severity
    - 'project.metric_change("scrutinizer.test_coverage", < 0)' # Code Coverage decreased from previous inspection
