language: php
dist: xenial
services:
  - mongodb
  - mysql
  - redis-server
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.3'
  - '7.4'
cache:
  directories:
    - vendor
before_install:
  - phpenv config-add php_config.ini
before_script:
  - composer install --no-interaction
