language: php
dist: xenial
php:
  - '5.6'
  - '7.0'
  - '7.1'
cache:
  directories:
    - vendor
before_install:
  - pecl install mongodb
  - phpenv config-add php_config.ini
before_script:
  - composer update
